# Generated by Django 4.2.4 on 2023-09-10 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Account Number')),
                ('payment_preferences', models.CharField(blank=True, choices=[('JAZZ_CASH', 'Jazz Cash'), ('EASY_PAISA', 'Easy Paisa')], max_length=50, null=True, verbose_name='Payment Preferences')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('SELLER', 'Seller/Merchant')], max_length=50)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=11)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=75, verbose_name='Company Name')),
                ('business_registration_number', models.CharField(max_length=50, verbose_name='Business Registration Number')),
                ('tax_identification_number', models.CharField(max_length=50, verbose_name='Tax Identification Number (TIN)')),
                ('business_type', models.CharField(choices=[('sole_proprietorship', 'Sole Proprietorship'), ('llc', 'Limited Liability Company (LLC)'), ('corporation', 'corporation')], max_length=50, verbose_name='Business Type')),
            ],
        ),
    ]
