# Generated by Django 4.2.4 on 2023-09-10 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('shipping_address', models.TextField(blank=True, null=True, verbose_name='Shipping Address')),
                ('billing_address', models.TextField(blank=True, null=True, verbose_name='Billing Address')),
                ('email_subscription', models.BooleanField(default=True, help_text='Subscribe to email updates and newsletters.', verbose_name='Email Subscription')),
                ('wishlist', models.ManyToManyField(blank=True, to='products.product', verbose_name='Wishlist')),
            ],
        ),
    ]
