# Generated by Django 4.2.4 on 2023-09-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_administrator_affiliatemarketer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerservicerepresentative',
            options={'verbose_name': 'Customer Service', 'verbose_name_plural': 'Customer Service'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SELLER', 'Seller/Merchant'), ('CUSTOMER', 'CUSTOMER/Shopper'), ('AFFILIATE_MARKETER', 'Affiliate Marketer'), ('CUSTOMER_SERVICE_REPRESENTATIVE', 'Customer Service Representative'), ('MARKETING_MANAGER', 'Marketing Manager'), ('PRODUCT_MANAGER', 'Product Manager'), ('SOCIAL_MEDIA_INFLUENCER', 'Social Media Influencer'), ('SALES_REPRESENTATIVE', 'Sales Representative'), ('LOGISTICS_COORDINATOR', 'Logistics Coordinator'), ('LEGAL_COUNSEL', 'Legal Counsel'), ('INVENTORY_MANAGER', 'Inventory Manager')], max_length=50),
        ),
    ]
