# Generated by Django 4.2.4 on 2023-09-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customerservicerepresentative_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SELLER', 'Seller/Merchant'), ('CUSTOMER', 'CUSTOMER/Shopper'), ('AFFILIATE_MARKETER', 'Affiliate Marketer'), ('CUSTOMER_SERVICE_REPRESENTATIVE', 'Customer Service Representative'), ('DELIVERY_DRIVER', 'Delivery Driver'), ('MARKETING_MANAGER', 'Marketing Manager'), ('PRODUCT_MANAGER', 'Product Manager'), ('SOCIAL_MEDIA_INFLUENCER', 'Social Media Influencer'), ('SALES_REPRESENTATIVE', 'Sales Representative'), ('LOGISTICS_COORDINATOR', 'Logistics Coordinator'), ('LEGAL_COUNSEL', 'Legal Counsel'), ('FINANCIAL_ANALYST', 'Financial Analyst'), ('DATA_ANALYST', 'Data Analyst'), ('INVENTORY_MANAGER', 'Inventory Manager')], max_length=50),
        ),
    ]
