# Generated by Django 4.2.4 on 2023-09-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='payment_preferences',
            field=models.CharField(blank=True, choices=[('CREDIT/DEBIT CARD', 'Credit/Debit Card'), ('JAZZCASH', 'Jazz Cash'), ('EASYPAISA', 'Easy Paisa'), ('CASH_ON_DELIVERY', 'Cash On Delivery')], max_length=50, null=True, verbose_name='Payment Preferences'),
        ),
    ]
