"""
Django settings for Core project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-^b%zm7mpce(@&)7ms6dpzz_5i1%oju=x)zkitvrj7h@z=wyqy7"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "products",
    "users",
    "custom_admin",
    "taggit",
    "orders",
    "smart_selects",
    "jazzmin",
    "nested_admin",
    "ckeditor",
    "django_extensions",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
    "/var/www/static/",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Authentiacation

AUTH_USER_MODEL = "users.User"
# AUTHENTICATION_BACKENDS = [
#     "django.contrib.auth.backends.ModelBackend",
#     "allauth.account.auth_backends.AuthenticationBackend",
# ]

# ACCOUNT_FORMS = {
#     "signup": "accounts.forms.SignupForm",
# }

# ACCOUNT_AUTHENTICATION_METHOD = "email"
# ACCOUNT_USERNAME_REQUIRED = False
# ACCOUNT_USER_MODEL_USERNAME_FIELD = None
# ACCOUNT_EMAIL_VERIFICATION = None
# ACCOUNT_EMAIL_REQUIRED = True
# LOGIN_REDIRECT_URL = "/"


JAZZMIN_SETTINGS = {
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fa-solid fa-people-group",
        "Products.Attribute": "fa-solid fa-table-list",
        "Products.Brand": "fa-solid fa-certificate",
        "Products.Category": "fa-solid fa-table-cells-large",
        "Products.Product": "fa-brands fa-product-hunt",
        "Products.VideoProvider": "fa-solid fa-video",
        "Taggit.Tag": "fa-solid fa-tags",
        # Users
        "Users.User": "fa-solid fa-users",
        "Users.Seller": "fa-solid fa-shop",
        "Users.Customer": "fa-solid fa-person",
        "Users.DeliveryDriver": "fa-solid fa-person-biking",
        "Users.Administrator": "fas fa-hat-cowboy",
        "Users.AffiliateMarketer": "fa-brands fa-affiliatetheme",
        "Users.CustomerServiceRepresentative": "fa-solid fa-headset",
        "Users.MarketingManager": "fa-solid fa-bullhorn",
        "Users.ProductManager": "fa-solid fa-user-tie",
        "Users.SocialMediaInfluencer": "fa-solid fa-user-secret",
        "Users.SalesRepresentative": "fa-brands fa-black-tie",
        "Users.LogisticsCoordinator": "fa-solid fa-truck",
        "Users.FinancialAnalyst": "fa-solid fa-coins",
        "Users.DataAnalyst": "fa-solid fa-dollar-sign",
        "Users.LegalCounsel": "fa-solid fa-scale-balanced",
        "Users.InventoryManager": "fa-solid fa-server",
    },
}
