# Generated by Django 4.2.4 on 2023-08-31 16:48

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='attribute',
            field=smart_selects.db_fields.ChainedForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attribute'),
        ),
    ]
