# Generated by Django 4.2.4 on 2023-08-31 16:51

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_attributevalue_attribute_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariation',
            old_name='attributes',
            new_name='attribute',
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='attribute_value',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='attribute', chained_model_field='attribute', on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='products.attributevalue'),
        ),
    ]
