# Generated by Django 4.2.4 on 2023-08-31 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_attributes_productvariation_attribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='attribute_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='products.attributevalue'),
        ),
    ]
