# Generated by Django 4.2.4 on 2023-08-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productvariation_attribute_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='attribute_value',
        ),
        migrations.AddField(
            model_name='attribute',
            name='values',
            field=models.ManyToManyField(related_name='attributes', to='products.attributevalue'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='attributes',
            field=models.ManyToManyField(related_name='product_variations', to='products.attributevalue'),
        ),
    ]
