# Generated by Django 4.2.4 on 2023-09-01 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_attribute_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variation', to='products.productvariation'),
        ),
    ]
