# Generated by Django 4.2.4 on 2023-09-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='review',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
